// Generated by https://quicktype.io

import { APIResponse } from "..";
import { ImageInProduct } from "./ImageInProducts";

export interface ListedProducts extends APIResponse {
  data: ListedProduct[];
}

export interface ListedProduct {
  id: string;
  title: string;
  price: number;
  images: ImageInProduct[];
}
